-- SCRIPT THAT CREATES A TRIGGER THAT DECREASES THE QUANTITY OF AN ITEM AFTER ADDING A NEW ORDER
CREATE TRIGGER store AFTER INSERT ON orders
FOR EACH ROW UPDATE items
SET quantity = quantity - NEW.number
WHERE name = NEW.item_name
