-- SCRIPT THAT CREATES A TRIGGER THAT RESETS THE ATTRIBUTE valid_email ONLY WHEN THE email HAS BEEN CHANGED
DELIMITER $$
CREATE TRIGGER reset_email BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
	IF NEW.email <> OLD.email THEN
		SET NEW.valid_email = 0;
	END IF;
END; $$
DELIMITER ;
